/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodos_numericos;
import java.math.BigInteger;
import java.math.BigDecimal;
import java.math.RoundingMode;
/**
 *
 * @author Alejandro Cupul
 */

public class Ventana extends javax.swing.JFrame {
    
    public double ValorAbsoluto(double a, double b){
        double Va;
        Va=Math.abs(a-b);
        return Va;
    }
    
    public double ValorRelativo(double a, double b){
        double Vr;
        Vr=(Math.abs(a-b))/a;
        return Vr;
    }
    
    public double ValorRelativoPorcentual(double a, double b){
        double Vrp;
        Vrp=((Math.abs(a-b))/a)*100;
        return Vrp;
    }
    
    public double Redondeo(double v, int d){
        BigDecimal bd = new BigDecimal(v);
        bd = bd.setScale(d, RoundingMode.HALF_UP);
	v= bd.doubleValue();
        return v;
    }
    
    public double Truncamiento(double v, int d){
        BigDecimal tr = new BigDecimal(v);
        tr = tr.setScale(d, RoundingMode.DOWN);
	v= tr.doubleValue();
        return v;
    }

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblValR = new javax.swing.JLabel();
        lblValA = new javax.swing.JLabel();
        CampoValR = new javax.swing.JTextField();
        CampoValA = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnCalcular = new javax.swing.JButton();
        lblValAbs = new javax.swing.JLabel();
        ResValAbs = new javax.swing.JLabel();
        lblValRel = new javax.swing.JLabel();
        ResValRel = new javax.swing.JLabel();
        lblValRelP = new javax.swing.JLabel();
        ResValRelP = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblRedondear = new javax.swing.JLabel();
        CampoDecRed = new javax.swing.JTextField();
        btnCalcularRed = new javax.swing.JButton();
        lblValAbs1 = new javax.swing.JLabel();
        ResValAbs1 = new javax.swing.JLabel();
        lblValRel1 = new javax.swing.JLabel();
        ResValRel1 = new javax.swing.JLabel();
        lblValRelP1 = new javax.swing.JLabel();
        ResValRelP1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblTruncar = new javax.swing.JLabel();
        CampoDecTrunc = new javax.swing.JTextField();
        btnCalcularTrunc = new javax.swing.JButton();
        lblValAbs2 = new javax.swing.JLabel();
        ResValAbs2 = new javax.swing.JLabel();
        lblValRel2 = new javax.swing.JLabel();
        ResValRel2 = new javax.swing.JLabel();
        lblValRelP2 = new javax.swing.JLabel();
        ResValRelP2 = new javax.swing.JLabel();
        btnCalcular1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Métodos Numéricos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Engravers MT", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("MÉTODOS NUMÉRICOS");

        lblValR.setBackground(new java.awt.Color(204, 204, 204));
        lblValR.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblValR.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValR.setText("Valor real:");

        lblValA.setBackground(new java.awt.Color(204, 204, 204));
        lblValA.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblValA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValA.setText("Valor aproximado:");

        CampoValR.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        CampoValA.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblValAbs.setBackground(new java.awt.Color(204, 204, 204));
        lblValAbs.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblValAbs.setForeground(new java.awt.Color(0, 0, 153));
        lblValAbs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValAbs.setText("Valor absoluto:");

        ResValAbs.setBackground(new java.awt.Color(204, 204, 204));
        ResValAbs.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ResValAbs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblValRel.setBackground(new java.awt.Color(204, 204, 204));
        lblValRel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblValRel.setForeground(new java.awt.Color(0, 0, 153));
        lblValRel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValRel.setText("Valor relativo:");

        ResValRel.setBackground(new java.awt.Color(204, 204, 204));
        ResValRel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ResValRel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblValRelP.setBackground(new java.awt.Color(204, 204, 204));
        lblValRelP.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblValRelP.setForeground(new java.awt.Color(0, 0, 153));
        lblValRelP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValRelP.setText("Valor relativo (%):");

        ResValRelP.setBackground(new java.awt.Color(204, 204, 204));
        ResValRelP.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ResValRelP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblRedondear.setBackground(new java.awt.Color(204, 204, 204));
        lblRedondear.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblRedondear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRedondear.setText("Redondear a:");

        CampoDecRed.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        CampoDecRed.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnCalcularRed.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCalcularRed.setText("CALCULAR");
        btnCalcularRed.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalcularRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularRedActionPerformed(evt);
            }
        });

        lblValAbs1.setBackground(new java.awt.Color(204, 204, 204));
        lblValAbs1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblValAbs1.setForeground(new java.awt.Color(0, 0, 153));
        lblValAbs1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValAbs1.setText("Valor absoluto:");

        ResValAbs1.setBackground(new java.awt.Color(204, 204, 204));
        ResValAbs1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ResValAbs1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblValRel1.setBackground(new java.awt.Color(204, 204, 204));
        lblValRel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblValRel1.setForeground(new java.awt.Color(0, 0, 153));
        lblValRel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValRel1.setText("Valor relativo:");

        ResValRel1.setBackground(new java.awt.Color(204, 204, 204));
        ResValRel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ResValRel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblValRelP1.setBackground(new java.awt.Color(204, 204, 204));
        lblValRelP1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblValRelP1.setForeground(new java.awt.Color(0, 0, 153));
        lblValRelP1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValRelP1.setText("Valor relativo (%):");

        ResValRelP1.setBackground(new java.awt.Color(204, 204, 204));
        ResValRelP1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ResValRelP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTruncar.setBackground(new java.awt.Color(204, 204, 204));
        lblTruncar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTruncar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTruncar.setText("Truncar a:");

        CampoDecTrunc.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        CampoDecTrunc.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnCalcularTrunc.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCalcularTrunc.setText("CALCULAR");
        btnCalcularTrunc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalcularTrunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTruncActionPerformed(evt);
            }
        });

        lblValAbs2.setBackground(new java.awt.Color(204, 204, 204));
        lblValAbs2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblValAbs2.setForeground(new java.awt.Color(0, 0, 153));
        lblValAbs2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValAbs2.setText("Valor absoluto:");

        ResValAbs2.setBackground(new java.awt.Color(204, 204, 204));
        ResValAbs2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ResValAbs2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblValRel2.setBackground(new java.awt.Color(204, 204, 204));
        lblValRel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblValRel2.setForeground(new java.awt.Color(0, 0, 153));
        lblValRel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValRel2.setText("Valor relativo:");

        ResValRel2.setBackground(new java.awt.Color(204, 204, 204));
        ResValRel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ResValRel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblValRelP2.setBackground(new java.awt.Color(204, 204, 204));
        lblValRelP2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblValRelP2.setForeground(new java.awt.Color(0, 0, 153));
        lblValRelP2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValRelP2.setText("Valor relativo (%):");

        ResValRelP2.setBackground(new java.awt.Color(204, 204, 204));
        ResValRelP2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ResValRelP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnCalcular1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCalcular1.setText("VACIAR");
        btnCalcular1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblValA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CampoValR)
                                    .addComponent(CampoValA)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ResValAbs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValRel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ResValRel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValRelP, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ResValRelP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCalcular)
                        .addGap(214, 214, 214))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValAbs1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ResValAbs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValRel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ResValRel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValRelP1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ResValRelP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValAbs2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ResValAbs2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValRel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ResValRel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValRelP2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ResValRelP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRedondear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoDecRed, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCalcularRed))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTruncar)
                                .addGap(25, 25, 25)
                                .addComponent(CampoDecTrunc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCalcularTrunc)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addComponent(btnCalcular1)
                .addGap(265, 265, 265))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValR, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoValR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblValA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoValA))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValAbs, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(ResValAbs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValRel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(ResValRel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValRelP, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(ResValRelP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRedondear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoDecRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularRed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValAbs1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(ResValAbs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValRel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(ResValRel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValRelP1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(ResValRelP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTruncar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoDecTrunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularTrunc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValAbs2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(ResValAbs2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValRel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(ResValRel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValRelP2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(ResValRelP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcular1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        double r, a, abs, rel, relpor;
        r=Double.parseDouble(CampoValR.getText());
        a=Double.parseDouble(CampoValA.getText());
        abs=ValorAbsoluto(r, a);
        rel=ValorRelativo(r, a);
        relpor=ValorRelativoPorcentual(r, a);
        ResValAbs.setText(String.valueOf(abs));
        ResValRel.setText(String.valueOf(rel));
        ResValRelP.setText(String.valueOf(relpor));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnCalcularRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularRedActionPerformed
        // TODO add your handling code here:
        double abs, rel, relpor, absR, relR, relporR;
        int dec;
        abs=Double.parseDouble(ResValAbs.getText());
        rel=Double.parseDouble(ResValRel.getText());
        relpor=Double.parseDouble(ResValRelP.getText());
        dec=Integer.parseInt(CampoDecRed.getText());
        absR=Redondeo(abs, dec);
        relR=Redondeo(rel, dec);
        relporR=Redondeo(relpor, dec);
        ResValAbs1.setText(String.valueOf(absR));
        ResValRel1.setText(String.valueOf(relR));
        ResValRelP1.setText(String.valueOf(relporR));
        
    }//GEN-LAST:event_btnCalcularRedActionPerformed

    private void btnCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular1ActionPerformed
        // TODO add your handling code here:
        CampoValR.setText("");
        CampoValA.setText("");
        ResValAbs.setText("");
        ResValRel.setText("");
        ResValRelP.setText("");
        ResValAbs1.setText("");
        ResValRel1.setText("");
        ResValRelP1.setText("");
        ResValAbs2.setText("");
        ResValRel2.setText("");
        ResValRelP2.setText("");
        CampoDecRed.setText("");
        CampoDecTrunc.setText("");
    }//GEN-LAST:event_btnCalcular1ActionPerformed

    private void btnCalcularTruncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTruncActionPerformed
        // TODO add your handling code here:
        double abs, rel, relpor, absT, relT, relporT;
        int dec;
        abs=Double.parseDouble(ResValAbs.getText());
        rel=Double.parseDouble(ResValRel.getText());
        relpor=Double.parseDouble(ResValRelP.getText());
        dec=Integer.parseInt(CampoDecTrunc.getText());
        absT=Truncamiento(abs, dec);
        relT=Truncamiento(rel, dec);
        relporT=Truncamiento(relpor, dec);
        ResValAbs2.setText(String.valueOf(absT));
        ResValRel2.setText(String.valueOf(relT));
        ResValRelP2.setText(String.valueOf(relporT));
    }//GEN-LAST:event_btnCalcularTruncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoDecRed;
    private javax.swing.JTextField CampoDecTrunc;
    private javax.swing.JTextField CampoValA;
    private javax.swing.JTextField CampoValR;
    private javax.swing.JLabel ResValAbs;
    private javax.swing.JLabel ResValAbs1;
    private javax.swing.JLabel ResValAbs2;
    private javax.swing.JLabel ResValRel;
    private javax.swing.JLabel ResValRel1;
    private javax.swing.JLabel ResValRel2;
    private javax.swing.JLabel ResValRelP;
    private javax.swing.JLabel ResValRelP1;
    private javax.swing.JLabel ResValRelP2;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcular1;
    private javax.swing.JButton btnCalcularRed;
    private javax.swing.JButton btnCalcularTrunc;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblRedondear;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTruncar;
    private javax.swing.JLabel lblValA;
    private javax.swing.JLabel lblValAbs;
    private javax.swing.JLabel lblValAbs1;
    private javax.swing.JLabel lblValAbs2;
    private javax.swing.JLabel lblValR;
    private javax.swing.JLabel lblValRel;
    private javax.swing.JLabel lblValRel1;
    private javax.swing.JLabel lblValRel2;
    private javax.swing.JLabel lblValRelP;
    private javax.swing.JLabel lblValRelP1;
    private javax.swing.JLabel lblValRelP2;
    // End of variables declaration//GEN-END:variables
}
